name: UltimateServerProtector
version: 24.1
author: OverwriteMC
main: ru.overwrite.protect.bukkit.ServerProtector
api-version: 1.13
folia-supported: true
load-priority: STARTUP
commands:
   ultimateserverprotector:
      aliases: [usp, serverprotector]